function ${function_name}_autoTestData
dataIn=repmat(struct(...
    'input',{{${input_generator}}},...
    'cmp',{{${output_cmp}}}...
    ),3,1);
mautogradeTestInOutMakeData(@${function_name},dataIn,...
    'fileSaveDir','../../autograders/${base_name}/');
