#!/usr/bin/env bash

# Get common setup variables (repository information)
cd /autograder/source
source setup_variables.sh

# Set up autograder files
SOURCE_DIR="${AUTOGRADER_DIR}/source"
RESULT_DIR="${AUTOGRADER_DIR}/results"
SUBMISSION_DIR="${AUTOGRADER_DIR}/submission"


# Make sure mAutograde and tests are up to date
cd "${MAUTOGRADE_DIR}"
git pull
cd "${MAUTOGRADE_TESTS_DIR}"
git pull

# Stage submission
cp "${SUBMISSION_DIR}"/* "${SOURCE_DIR}"
cd "${SOURCE_DIR}"

# Run tests
octave --no-gui --eval "mautogradeSuiteRunTests $MAUTOGRADE_TESTS_DIR" > "${RESULT_DIR}"/results.json

# Additionally, we can allow custom additions to the results, as desired by a user's implementation.
# Create and implement the following function in whatever directory generates the autograder.zip file.
./mautograder_additional_tests.py "${RESULT_DIR}"/results.json